// import { Inter } from "next/font/google";

import StoreProvider from "./Providers/StoreProvider";
import SWRProvider from "./Providers/SWRProvider";
import "./styles/globals.css";
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sfotipy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <SWRProvider>{children}</SWRProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
